"""Shared project name mappings — used by all architectures and tools.

Centralizes the project-to-API-args mapping so that modules don't need
to import from each other (avoiding circular deps and heavy deps like mcp).
"""

from __future__ import annotations

# GitHub: project name → (owner, repo)
GITHUB_REPO_MAP: dict = {
    "react": ("facebook", "react"),
    "vue": ("vuejs", "core"),
    "svelte": ("sveltejs", "svelte"),
    "angular": ("angular", "angular"),
    "next.js": ("vercel", "next.js"),
    "nextjs": ("vercel", "next.js"),
    "nuxt": ("nuxt", "nuxt"),
    "sveltekit": ("sveltejs", "kit"),
    "express": ("expressjs", "express"),
    "express.js": ("expressjs", "express"),
    "fastify": ("fastify", "fastify"),
    "koa": ("koajs", "koa"),
    "django": ("django", "django"),
    "flask": ("pallets", "flask"),
    "fastapi": ("fastapi", "fastapi"),
    "deno": ("denoland", "deno"),
    "bun": ("oven-sh", "bun"),
    "node.js": ("nodejs", "node"),
    "nodejs": ("nodejs", "node"),
    "vite": ("vitejs", "vite"),
    "webpack": ("webpack", "webpack"),
    "turbopack": ("vercel", "turborepo"),
    "prisma": ("prisma", "prisma"),
    "drizzle": ("drizzle-team", "drizzle-orm"),
    "typeorm": ("typeorm", "typeorm"),
    "sequelize": ("sequelize", "sequelize"),
    "redux": ("reduxjs", "redux"),
    "zustand": ("pmndrs", "zustand"),
    "jotai": ("pmndrs", "jotai"),
    "recoil": ("facebookexperimental", "Recoil"),
    "tailwind": ("tailwindlabs", "tailwindcss"),
    "tailwind css": ("tailwindlabs", "tailwindcss"),
    "tailwindcss": ("tailwindlabs", "tailwindcss"),
    "bootstrap": ("twbs", "bootstrap"),
    "jest": ("jestjs", "jest"),
    "vitest": ("vitest-dev", "vitest"),
    "playwright": ("microsoft", "playwright"),
    "lodash": ("lodash", "lodash"),
    "axios": ("axios", "axios"),
    "tensorflow.js": ("tensorflow", "tfjs"),
    "tensorflowjs": ("tensorflow", "tfjs"),
    "remix": ("remix-run", "remix"),
}

# npm: project name → npm package name
NPM_PACKAGE_MAP: dict = {
    "react": "react",
    "vue": "vue",
    "svelte": "svelte",
    "angular": "@angular/core",
    "next.js": "next",
    "nextjs": "next",
    "nuxt": "nuxt",
    "sveltekit": "@sveltejs/kit",
    "express": "express",
    "express.js": "express",
    "fastify": "fastify",
    "koa": "koa",
    "deno": "deno",
    "bun": "bun",
    "vite": "vite",
    "webpack": "webpack",
    "turbopack": "turbopack",
    "prisma": "@prisma/client",
    "drizzle": "drizzle-orm",
    "typeorm": "typeorm",
    "sequelize": "sequelize",
    "redux": "redux",
    "zustand": "zustand",
    "jotai": "jotai",
    "recoil": "recoil",
    "tailwind": "tailwindcss",
    "tailwind css": "tailwindcss",
    "tailwindcss": "tailwindcss",
    "bootstrap": "bootstrap",
    "jest": "jest",
    "vitest": "vitest",
    "playwright": "playwright",
    "lodash": "lodash",
    "axios": "axios",
    "tensorflow.js": "@tensorflow/tfjs",
    "tensorflowjs": "@tensorflow/tfjs",
    "remix": "@remix-run/react",
}

# OSV: project name → (package_name, ecosystem)
OSV_PACKAGE_MAP: dict = {
    "react": ("react", "npm"),
    "vue": ("vue", "npm"),
    "svelte": ("svelte", "npm"),
    "angular": ("@angular/core", "npm"),
    "next.js": ("next", "npm"),
    "nextjs": ("next", "npm"),
    "nuxt": ("nuxt", "npm"),
    "express": ("express", "npm"),
    "express.js": ("express", "npm"),
    "fastify": ("fastify", "npm"),
    "koa": ("koa", "npm"),
    "django": ("django", "PyPI"),
    "flask": ("flask", "PyPI"),
    "fastapi": ("fastapi", "PyPI"),
    "vite": ("vite", "npm"),
    "webpack": ("webpack", "npm"),
    "prisma": ("@prisma/client", "npm"),
    "drizzle": ("drizzle-orm", "npm"),
    "typeorm": ("typeorm", "npm"),
    "sequelize": ("sequelize", "npm"),
    "redux": ("redux", "npm"),
    "zustand": ("zustand", "npm"),
    "jotai": ("jotai", "npm"),
    "recoil": ("recoil", "npm"),
    "tailwindcss": ("tailwindcss", "npm"),
    "tailwind": ("tailwindcss", "npm"),
    "bootstrap": ("bootstrap", "npm"),
    "jest": ("jest", "npm"),
    "vitest": ("vitest", "npm"),
    "playwright": ("playwright", "npm"),
    "lodash": ("lodash", "npm"),
    "axios": ("axios", "npm"),
    "tensorflow.js": ("@tensorflow/tfjs", "npm"),
    "remix": ("@remix-run/react", "npm"),
    "deno": ("deno", "npm"),
    "bun": ("bun", "npm"),
    "node.js": ("node", "npm"),
}

# StackOverflow: project name → SO tag
SO_TAG_MAP: dict = {
    "react": "reactjs",
    "vue": "vue.js",
    "svelte": "svelte",
    "angular": "angular",
    "next.js": "next.js",
    "nextjs": "next.js",
    "nuxt": "nuxt.js",
    "sveltekit": "sveltekit",
    "express": "express",
    "express.js": "express",
    "fastify": "fastify",
    "koa": "koa",
    "django": "django",
    "flask": "flask",
    "fastapi": "fastapi",
    "deno": "deno",
    "bun": "bun",
    "vite": "vite",
    "webpack": "webpack",
    "prisma": "prisma",
    "drizzle": "drizzle-orm",
    "typeorm": "typeorm",
    "sequelize": "sequelize.js",
    "redux": "redux",
    "zustand": "zustand",
    "jotai": "jotai",
    "recoil": "recoiljs",
    "tailwindcss": "tailwind-css",
    "tailwind": "tailwind-css",
    "tailwind css": "tailwind-css",
    "bootstrap": "bootstrap-5",
    "jest": "jestjs",
    "vitest": "vitest",
    "playwright": "playwright",
    "lodash": "lodash",
    "axios": "axios",
    "tensorflow.js": "tensorflow.js",
    "remix": "remix",
    "node.js": "node.js",
}
